### ISSUE TITLE
pdm shell doesn't spawn a shell

### ISSUE THREAD

**Issue by deronnax** [abersheeran/pdm-shell#3]
Hi.
I ran into this plugin, hoping to give pdm a `shell` command, the same than exists in pipenv, poetry or hatch: spawn a sub shell, with the current virtualenv loaded. I was also redirected to pdm-shell by PDM maintainers thinking that was what pdm-shell was doing. 
Howerever, `pdm shell` outputs what seems to be some shell commands and no shell is spawned. There is then a mismatch between the plugin title/the command, and the behavior.
People expect `pdm shell` to behave like `pipenv shell`, `poetry shell` and `hatch shell`.

**Comment by abersheeran** [comment]
This is not the goal of pdm-shell. The current function is determined after careful consideration. It refers to the opinions of the PDM authors. It provides a way to enter the current environment in the simplest and most portable way.
By the way, since PDM takes virtual environments by default, it should be easier to use the way virtual environments are activated (and there are plenty of tried and tested practices here).

**Comment by deronnax** [comment]
OK. I plan to write a `pdm-shell` plugin that spawns a shell with virtualenv activated, as other package managers do. The customer I work for is heavily reliant on the `xxx shell` workflow, and I also think there a handsome of developers would like to have a pdm shell too. Would you accept to rename your project on PyPI so this pdm shell project can have the `pdm-shell` name on PyPI?

**Comment by abersheeran** [comment]
You can name your new project `pdm-venv-shell` 😊
